name: CICD with CDK
run-name: ${{ github.actor }} pushed a change via GitHub Actions 🚀
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-ecr-repo
          IMAGE_TAG: ${{ github.sha }}
        # an action can be added here to test the image before building
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  infra-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1

      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install -g aws-cdk
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: venv
        id: venv
        run: |-
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
          pip install aws-cdk.lambda-layer-kubectl-v31
          cdk bootstrap
          cdk diff
          cdk synth
      
      - run: echo "🍏 This job's status is ${{ job.status }}."

  Deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1

      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install -g aws-cdk
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: venv
        id: venv
        run: |-
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
          pip install aws-cdk.lambda-layer-kubectl-v31
          cdk deploy --require-approval never

      - run: echo "🍏 This job's status is ${{ job.status }}."
